### ISSUE TITLE
Used values cause KeyNotFoundException

### ISSUE THREAD

**Issue by Demkeys** [gotolabs-io/gotostudio#1]
To reproduce:
- Create 3 float values (a,b,c) in an ExpressionAction.
- Enter expression "a+b".
- Set output to some float variable.
- Enter Play Mode.
Console window will show "KeyNotFoundException: The given key was not present in the dictionary".

**Comment by JuhaKiili** [comment]
Fixed by https://github.com/gotolabs-io/gotostudio/commit/7a36f90ecf74c50e7409856f249de2b76b74464b

**Comment by JuhaKiili** [comment]
Fixed by https://github.com/gotolabs-io/gotostudio/commit/7a36f90ecf74c50e7409856f249de2b76b74464b
